baseurl = "https://das-hep.gitlab.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "DAS-HEP"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true


[Params]
  subtitle = "Distributed Analysis Scheme for High Energy Physics"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  commit = false
  rss = true
  comments = true


[Author]
  name = "The DAS-HEP Authors"


[[menu.main]]
    name = "Posts"
    url = "post/"
    weight = 1  


[[menu.main]]
    name = "Courses"
    url = "course/"
    weight = 2

[[menu.main]]  
    name = "Schools"
    url = "school/" 
    weight = 3 







